<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cocktail_bdfl"
 *
 * Auto generated by Extension Builder 2020-01-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'cocktail bdfl',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Florentin BALFOUONG, Daphné AUBERT, Lucas ROSSIGNOL, Benjamin ROOSEBROUCK',
    'author_email' => 'florentin.balfouong@etu.u-bordeaux.fr, daphne.aubert@etu.u-bordeaux.fr, lucas.rossignol@etu.u-bordeaux.fr, benjamin.roosebrouck@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
